services:

  # listens to mqtt packets and saves to database
  meshtastic-mqtt:
    container_name: meshtastic-mqtt
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/mqtt.sh
    environment:
      DATABASE_URL: "mysql://root:${MARIADB_ROOT_PASSWORD:-password}@database:3306/${MARIADB_DATABASE:-meshtastic-map}?connection_limit=100"
      MQTT_OPTS: "${MQTT_OPTS:-}" # add custom mqtt.js options here, e.g. --mqtt-topic msh/+/2/e/# --mqtt-client-id meshtastic-map-my-host
      AUTO_FETCH_PROTOBUFS: "${AUTO_FETCH_PROTOBUFS:-true}"
      PROTOBUFS_REPO_URL: "${PROTOBUFS_REPO_URL:-https://github.com/meshtastic/protobufs}"
      PROTOBUFS_GIT_REF: "${PROTOBUFS_GIT_REF:-}"
      PROTOBUFS_CLONE_PATH: "${PROTOBUFS_CLONE_PATH:-/app/src/external/protobufs}"

  # runs the web map ui
  meshtastic-map:
    container_name: meshtastic-map
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/map.sh
    ports:
      - 127.0.0.1:${MAP_PORT:-8081}:8080/tcp
    environment:
      DATABASE_URL: "mysql://root:${MARIADB_ROOT_PASSWORD:-password}@database:3306/${MARIADB_DATABASE:-meshtastic-map}?connection_limit=100"
      MAP_OPTS: "${MAP_OPTS:-}" # add any custom index.js options here

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: bitnami/mariadb
    ports:
      - 127.0.0.1:${DATABASE_PORT:-3306}:3306/tcp
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE:-meshtastic-map}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-password}"
    volumes:
      - database_data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 5s

volumes:
  database_data:
